### PR TITLE
serdect: return the deserialized buffer during deserialization

### LINKED ISSUE #1322: serdect: `slice::deserialize_hex_or_bin` needs to return the amount of deserialized data
This is tracking a regression from #1112, where `slice::deserialize_hex_or_bin` was changed to return `Result<(), D::Error>` instead of `Result<&[u8], D::Error>`.

Notably this API is intended for use cases where the amount of deserialized data can vary, and may be shorter than the provided `buffer` parameter. The ability to handle messages shorter than `buffer` has been lost.

See https://github.com/RustCrypto/formats/pull/1112#discussion_r1446473939

### PR DESCRIPTION
**Pull request by fjarri**
Fixes #1322

Also fixed a TODO in `StrIntoBufVisitor::visit_str` by mapping `base16ct` errors to `serde` errors.

### CODE REVIEW

File: serdect/src/common.rs [hunk 1]
```diff
@@ -84,13 +84,15 @@ impl<'de, 'b, T: LengthCheck> Visitor<'de> for StrIntoBufVisitor<'b, T> {
...
-        // TODO: Map `base16ct::Error::InvalidLength` to `Error::invalid_length`.
-        base16ct::mixed::decode(v, self.0)
-            .map(|_| ())
-            .map_err(E::custom)
+        base16ct::mixed::decode(v, self.0).map_err(|err| match err {
+            base16ct::Error::InvalidLength => {
+                Error::invalid_length(v.len(), &"an even number of hex digits")
+            }
+            base16ct::Error::InvalidEncoding => Error::invalid_value(
+                Unexpected::Str(v),
```
Comment (fjarri) [inline serdect/src/common.rs:92]: Actually, can this be secret? Should we not return it?

Comment (fjarri) [reply serdect/src/common.rs]: Replaced with a placeholder.

**Review by tarcieri — APPROVED** [review]
